# Generated by Django 5.1.7 on 2025-07-13 12:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0003_alter_contactmessage_booking"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="contactmessage",
            old_name="submitted_at",
            new_name="created_at",
        ),
        migrations.AddField(
            model_name="contactmessage",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contact_messages",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="contactmessage",
            name="additional_notes",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="contactmessage",
            name="booking",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contact_messages",
                to="bookings.booking",
            ),
        ),
        migrations.AlterField(
            model_name="contactmessage",
            name="dietary_preferences",
            field=models.TextField(),
        ),
    ]
